version: '2'

services:
    django:
        build: ./django
        command: python manage.py runserver 0.0.0.0:8000
        expose:
            - "8000"
        volumes:
            - ./django:/code/

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "8080:80"
        links:
            - django:django
